# Generated by Django 2.1 on 2018-12-16 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=300)),
                ('card_type', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('cash_withdrawal_limit_per_transaction', models.FloatField(blank=True, null=True)),
                ('cash_withdrawal_limit_per_day', models.FloatField(blank=True, null=True)),
                ('max_credit_limit', models.FloatField(blank=True, null=True)),
                ('international_transaction_available', models.BooleanField(default=False)),
                ('balance_transfer_available', models.BooleanField(default=False)),
                ('dual_currency', models.BooleanField(default=False)),
                ('reward_supplementary_card', models.BooleanField(default=False)),
                ('reward_airport_lounge', models.BooleanField(default=False)),
                ('reward_cashback_available', models.BooleanField(default=False)),
                ('reward_luxary_resort_hotel', models.BooleanField(default=False)),
                ('reward_insurance_plan', models.BooleanField(default=False)),
                ('reward_travel_benefits', models.BooleanField(default=False)),
                ('reward_fine_dining', models.BooleanField(default=False)),
                ('reward_buffet_discount', models.BooleanField(default=False)),
                ('reward_medical_discount', models.BooleanField(default=False)),
                ('reward_shopping', models.BooleanField(default=False)),
                ('reward_airlines_ticket', models.BooleanField(default=False)),
                ('reward_point_program', models.BooleanField(default=False)),
                ('reward_emi_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(through='recommender.Recommendation', to=settings.AUTH_USER_MODEL),
        ),
    ]
