# Generated by Django 2.1 on 2018-12-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
