# Generated by Django 2.1 on 2018-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cash_withdrawal_limit_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cash_withdrawal_limit_per_transaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='max_credit_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
