feature_list = {
        
        
        "international transaction":'international_transaction_available', 
        "balance transfer":'balance_transfer_available',
        "dual currency":'dual_currency', 
	    "supplementary card":'reward_supplementary_card', 
	    "airport lounge":'reward_airport_lounge',
        "cashback":'reward_cashback_available', 
	    "luxary resort hotel":'reward_luxary_resort_hotel',
        "insurance plan":'reward_insurance_plan', 
	    "travel benefit":'reward_travel_benefits', 
	    "fine dining":'reward_fine_dining',
        "buffet discount":'reward_buffet_discount', 
	    "medical discount":'reward_medical_discount', 
	    "shopping":'reward_shopping',
        "airlines ticket":'reward_airlines_ticket', 
	    "point program":'reward_point_program',
        "emi available":'reward_emi_available', 
	    "hajj facility":'hajj_card', 
	    "visa":'is_visa', 
	    "mastercard":'is_mastercard',
        "AB Bank":'bank_name_AB Bank',
        "Agrani Bank":'bank_name_Agrani Bank Limited',
        "BRAC Bank":'bank_name_BRAC Bank Limited',
        "Bangladesh Krishi Bank":'bank_name_Bangladesh Krishi Bank',
        "Bank Asia":'bank_name_Bank Asia Limited',
        "City Bank":'bank_name_City Bank Limited',
        'bank_name_Dhaka Bank',
        'bank_name_Dutch Bangla Bank Limited',
        'bank_name_IFIC Bank Limited', 
        'bank_name_Jamuna Bank Limited',
        'bank_name_Janata Bank Limited', 
        'bank_name_Meghna Bank',
        'bank_name_Midland Bank', 
        'bank_name_Modhumoti Bank',
        'bank_name_Mutual Trust bank Limited', 
        'bank_name_NRB Bank Limited',
        'bank_name_NRB Commercial Bank Limited',
        'bank_name_National Credit and Commerce Bank Limited',
        'bank_name_One Bank', 
        'bank_name_Premier Bank', 
        'bank_name_Prime Bank',
        'bank_name_Pubali Bank Limited', 
        'bank_name_Rupali Bank Limited',
        'bank_name_Sonali Bank Limited', 
        'bank_name_Standard Charter',
        'bank_name_Trust Bank', 
        'bank_name_United Commercial Bank Limited',
        'card_type_Credit', 
        'card_type_Debit', 
        'card_type_Prepaid',
        'interest_rate_1-10', 
        'interest_rate_11-20', 
        'interest_rate_21-30',
        'interest_rate_zero', 
        'max_credit_limit_0-100000',
        'max_credit_limit_100000-500000', 
        'max_credit_limit_1000000+',
        'max_credit_limit_N/A', 
        'max_credit_limit_unknown'}
